server.port=8080
spring.application.name=hospital-gateway

# URLs de los microservicios
services.auth.url=http://localhost:8081/api/auth
services.patient.url=http://localhost:8082/api/patients
services.notification.url=http://localhost:8083/api/notifications
